#!/bin/bash

code=`curl -o /dev/null --silent --head --write-out '%{http_code}' $*`

case $code in
  2??)
    echo "OK - $code"
    exit 0
  ;;
  3??)
    echo "WARNING - $code"
    exit 1
  ;;
  5??)
    echo "CRITICAL - $code"
    exit 2
  ;;
  *)
    echo "UNKNOWN - $code"
    exit 3
  ;;
esac
