#!/bin/bash

code=`curl -o /dev/null --silent --head --write-out '%{http_code}' $*`

case $code in
  [200-299]*)
    echo "OK - $code"
    exit 0
  ;;
  [300-399]*)
    echo "WARNING - $code"
    exit 1
  ;;
  [500-599]*)
    echo "CRITICAL - $code"
    exit 2
  ;;
  *)
    echo "UNKNOWN - $code"
    exit 3
  ;;
esac
